name: Build Desktop Apps

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: |
        if [ "${{ matrix.platform }}" = "win" ]; then
          npm run build:win
        elif [ "${{ matrix.platform }}" = "mac" ]; then
          npm run build:mac
        else
          npm run build:linux
        fi
      shell: bash

    - name: Upload Windows artifact
      if: matrix.platform == 'win'
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: |
          dist/*.exe
          dist/win-unpacked/

    - name: Upload Mac artifact
      if: matrix.platform == 'mac'
      uses: actions/upload-artifact@v4
      with:
        name: mac-app
        path: |
          dist/*.dmg
          dist/mac/

    - name: Upload Linux artifact
      if: matrix.platform == 'linux'
      uses: actions/upload-artifact@v4
      with:
        name: linux-app
        path: |
          dist/*.AppImage
          dist/linux-unpacked/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-app/dist/*.exe
          mac-app/dist/*.dmg
          linux-app/dist/*.AppImage
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}